### ISSUE TITLE
Run flow-tests via FireX

### ISSUE THREAD

**Issue by mabouels** [FireXStuff/firexapp#7]
Will get parallelization as a side effect.

**Comment by MarcDelahousse** [comment]
I'm curious. Could you elaborate. Flow tests trigger a FireX run. Do you mean create a task to run a set of tests (that then trigger the FireX runs) ?

**Comment by mabouels** [comment]
Yes, currently, flow-tests ran sequentially. By creating FireX tasks, you can run them in parallel, in addition to quite a bit of added benefits.

Created [firex-bundle-ci](https://github.com/FireXStuff/firex-bundle-ci/tree/main/firex_bundle_ci) to achieve that.
